version: '3'
services:
    mysql1:
        container_name: mysql1
        hostname: mysql1-container
        image: mysql:5.7
        ports: 
            # <Port exposed> : < MySQL Port running inside container>
            - 31216:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            # - MYSQL_REPLICATION_MODE=master
            # - MYSQL_REPLICATION_USER=replication
            # - MYSQL_REPLICATION_PASSWORD=testpassword
        volumes:
            - ./docker/data/mysql1:/var/lib/mysql
            - ./docker/conf/mysql/master.cnf:/etc/mysql/my.cnf

    mysql2:
        container_name: mysql2
        hostname: mysql2-container
        image: mysql:5.7
        ports: 
            - 31217:3306
        depends_on: 
            - mysql1
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            # - MYSQL_REPLICATION_MODE=slave
            # - MYSQL_REPLICATION_USER=replication
            # - MYSQL_REPLICATION_PASSWORD=testpassword
            # - MYSQL_MASTER_HOST=mysql1
            # - MYSQL_MASTER_PORT_NUMBER=31216
            # - MYSQL_MASTER_ROOT_PASSWORD=root
        volumes:
            - ./docker/data/mysql2:/var/lib/mysql
            - ./docker/conf/mysql/slave.cnf:/etc/mysql/my.cnf